### ISSUE TITLE
"'accountId' must be the only user identifying query parameter in GDPR strict mode."

### ISSUE THREAD

**Issue by lemaral** [fourplusone/terraform-provider-jira#22]
Trying to execute the sample in README on Jira Cloud:

resource "jira_project_category" "category" {
  name = "Managed"
  description = "Managed Projects"
}

resource "jira_project" "project_a" {
  key = "TRF"
  name = "Terraform"
  project_type_key = "business"
  project_template_key = "com.atlassian.jira-core-project-templates:jira-core-project-management"
  lead = "bot"
  permission_scheme = 10400
  notification_scheme = 10300
  category_id = "${jira_project_category.category.id}"
}
I get the following error
"'accountId' must be the only user identifying query parameter in GDPR strict mode."

**Comment by fourplusone** [comment]
I pushed a fix but unfortunately it does not pass CI (I suspect because of an unrelated issue). I will publish a new version of terraform-provider-jira as soon the CI issue has been resolved

**Comment by fourplusone** [comment]
Fixed in [v0.1.13](https://github.com/fourplusone/terraform-provider-jira/releases/tag/v0.1.13)
