### ISSUE TITLE
unsupported protocol scheme ""

### ISSUE THREAD

**Issue by augustgerro** [fourplusone/terraform-provider-jira#23]
When I try to use code from Reademe's example I receive next issue:
<img width="1048" alt="Pasted_Image_20_05_20__17_37" src="https://user-images.githubusercontent.com/3669104/82459467-aa502980-9ac0-11ea-84c6-d47709c8ba15.png">

Error:
```
Request failed: Creating Request failed: Post /***/rest/api/2/issuetype: unsupported protocol scheme ""
```
Code:
```HCL
// The types will be globally available in JIRA
resource "jira_issue_type" "task" {
  description = "A Task."
  name = "Task"
  avatar_id = 10318
}

resource "jira_issue_link_type" "blocks" {
  name = "Blocks"
  inward = "is blocked by"
  outward = "blocks"
}

resource "jira_issue" "example" {
  issue_type  = "${jira_issue_type.task.name}"
  project_key = "EXM"
  summary     = "Created using Terraform"

  // description is optional  
  description = "This is a test issue" 

  // (optional) Instead of deleting the issue, perform this transition 
  delete_transition = 21

  // (optional) Make sure, the issue is in the desired state
  // using state_transition
  state = 10000
  state_transition = 31 
}
```

**Comment by fourplusone** [comment]
Please make sure that JIRA_URL starts with https:// or http://

**Comment by augustgerro** [comment]
Thank you! My mistake, I forgot to specify https.

**Comment by augustgerro** [comment]
Can I ask here, how to use this parameter, I try to set some status to an issue (like backlog, to do, done, etc), but don't realize how to do that? 

Does this have something to do with these parameters?
```
  state = 10000
  state_transition = 31 
```

**Comment by fourplusone** [comment]
`state` refers to the id of the desired state. You can find the id of a state using the JIRA REST API using `<JIRA_URL>/rest/api/2/status`

`state_transition` refers to the transition that must be performed to react the state. To find the id of a transition you can use the REST API as well: `<JIRA_URL>/rest/api/2/issue/MYISSUE-1/transitions` where `<MYISSUE-1>` should refer to a newly created ticket
