### ISSUE TITLE
Question: Can I 'ensure' the members of a group looks a certain way ?

### ISSUE THREAD

**Issue by sonicjolt** [fourplusone/terraform-provider-jira#4]
I have a scenario where we have a shared Jira Cloud instance in the organization, and from time to time someone will mess up some memberships, .. add a user to the wrong group.

How does this provider react when a group is different from what is in the state-file ?

What I am looking for is to "ensure group memberships", by which I want to both add memberships, and remove memberships that don't match.

Is this possible ? Or is it something that needs to be added ?

**Comment by fourplusone** [comment]
At the moment, the provider ensures, that a user is present within the specified group. It does not prevent other users being added, however if a user is removed from a group and is still present within the .tf file it will be added again.

**Comment by sonicjolt** [comment]
It seems fairly intuitive, and non-destructive, which is what I generally expect from terraform's providers. 

But would it be worth considering an attribute for `jira_group` ala:

```
resource "jira_group" "tf_group" {
  name = "Terraform Managed"
  enforce_strict_memberships = true
}
```

Which could result in removal of manually added members to a Jira Group ?

**Comment by fourplusone** [comment]
I would prefer something like
