### ISSUE TITLE
Add support personal access token

### ISSUE THREAD

**Issue by gonchik** [fourplusone/terraform-provider-jira#53]
Hi! 
it will be great, if you add support that fucntionality

https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html

**Comment by dmlayton** [comment]
Looks like this [line](https://github.com/fourplusone/terraform-provider-jira/blob/84146b68bb8a572006a1208845c048d1abf635a3/jira/config.go#L23) is the culprit: 
`jiraClient.Authentication.SetBasicAuth(d.Get("user").(string), d.Get("password").(string))`

setBasicAuth is defined simple as: 
`func (s *AuthenticationService) SetBasicAuth(username, password string) {
	s.username = username
	s.password = password
	s.authType = authTypeBasic
}`

So we need some condition on which to use the [go-jira beaerer example](https://github.com/andygrunwald/go-jira/blob/58a11816d07fa32498b350a9af8afd7005e1e4bf/onpremise/examples/bearerauth/main.go) instead.

**Comment by dmlayton** [comment]
Fantastic, works great! Thank you so much. This project is so helpful -- makes JIRA usable/maintainable.
