### ISSUE TITLE
Support for arm64/mac M1?

### ISSUE THREAD

**Issue by bliq00** [fourplusone/terraform-provider-jira#55]
with this block 
terraform {
  required_providers {
    jira = {
      source = "fourplusone/jira"
    }
  }
  required_version = ">= 0.14"
}

I get an error of 

Error: Incompatible provider version
│
│ Provider registry.terraform.io/fourplusone/jira v0.1.15 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this
│ provider may have different platforms supported.

Is there any plan to make a compatible package?  I haven't seen a resolution or discussion for this issue.  please feel free to point me in that direction if one exists.  I'm on terraform 1.1.8 if it matters.  thanks.

**Comment by Hyog0** [comment]
have you find how to fix it @bliq00 ?  because i have the same issue 😄

**Comment by fourplusone** [comment]
The latest version (v0.1.16) supports M1
