### ISSUE TITLE
Projects do not support import 

### ISSUE THREAD

**Issue by adam-skalicky** [fourplusone/terraform-provider-jira#57]
Hi Folks,

When testing out Jira projects, I found that I cannot import existing projects. This seems to be something that is present with other resources so I figured I'd raise an issue.

**Steps to reproduce:**

Have an existing project in Jira.

- Via the CLI in your Terraform project, run terraform import jira_project.project_res_name project_id

 **Expected result:**
- Terraform will import the project.

**Actual result:**
The following error is shown:
`Error: resource jira_project doesn't support import`

Using Terraform v1.0.11 with Jira Server v8.20.8 with provider version 0.1.15

**Comment by adam-skalicky** [comment]
I did open this PR, I have tested it and it does appear to work, however the lead field does not appear to come through. That is what lead me to open https://github.com/fourplusone/terraform-provider-jira/issues/56


https://github.com/fourplusone/terraform-provider-jira/pull/58

**Comment by fourplusone** [comment]
Fixed by #58
