### ISSUE TITLE
Feature Request: Component

### ISSUE THREAD

**Issue by raypettersen** [fourplusone/terraform-provider-jira#70]
Thanks for developing and maintaining this project, it has worked very well for us.

One thing that would be a great addition to the current feature-set is managing components. Would it be possible to add that functionality as a resource, attachable to a project?

**Comment by raypettersen** [comment]
Great! 👍

**Comment by fourplusone** [comment]
The feature is now available on the `feature/component` branch.

**Comment by raypettersen** [comment]
Thank you!
