### ISSUE TITLE
error "'accountId' must be the only user identifying query parameter in GDPR strict mode" when create component

### ISSUE THREAD

**Issue by SLHolmess** [fourplusone/terraform-provider-jira#76]
Trying to execute the sample in README:
resource "jira_component" "example_component" {
  
  name = "Sample Component"
  project_key = "${jira_project.example.key}"
  
  // (optional) Description of the component
  description = "Sample Description" 
  
  // (optional) Component lead
  lead = "${jira_user.demo_user.name}"

  // (optional) assignee type. Can be one of project_default, component_lead, project_lead or unassigned.
	assignee_type = "component_lead"
}

I get the following error "'accountId' must be the only user identifying query parameter in GDPR strict mode." when add component lead

**Comment by raypettersen** [comment]
You've duplicated my ticket #74 

Suggest closing this one and upvoting #74 ?
